import cmd_terminal_page
import edit_conf_page
import entry_real_info_page
import fs_real_log_page
import new_module_form
import sys_info_page
import time_zone_set_form
import sip_interface_auto_conf_form
from fs_conf_form import FsConf
